// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACXv-U3CvH7ACC4k6Cv4-5u6AaugSdMUU',
    appId: '1:589151962230:web:7779237c33324cc7ad4b57',
    messagingSenderId: '589151962230',
    projectId: 'exameneasybite',
    authDomain: 'exameneasybite.firebaseapp.com',
    storageBucket: 'exameneasybite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL0-tJ3Eg3qxIhtVYNeO8K_MKE4OVWFuo',
    appId: '1:589151962230:android:b29191a62027b70bad4b57',
    messagingSenderId: '589151962230',
    projectId: 'exameneasybite',
    storageBucket: 'exameneasybite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBanXsf3I8VRHs-XeaEwWrIVZLco_WjRwE',
    appId: '1:589151962230:ios:cdf369e2cc1db780ad4b57',
    messagingSenderId: '589151962230',
    projectId: 'exameneasybite',
    storageBucket: 'exameneasybite.firebasestorage.app',
    iosBundleId: 'com.example.flExamenFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBanXsf3I8VRHs-XeaEwWrIVZLco_WjRwE',
    appId: '1:589151962230:ios:cdf369e2cc1db780ad4b57',
    messagingSenderId: '589151962230',
    projectId: 'exameneasybite',
    storageBucket: 'exameneasybite.firebasestorage.app',
    iosBundleId: 'com.example.flExamenFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACXv-U3CvH7ACC4k6Cv4-5u6AaugSdMUU',
    appId: '1:589151962230:web:e0d88926c578e4abad4b57',
    messagingSenderId: '589151962230',
    projectId: 'exameneasybite',
    authDomain: 'exameneasybite.firebaseapp.com',
    storageBucket: 'exameneasybite.firebasestorage.app',
  );
}
